// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DoLogin(arg1, arg2) {
  return window['go']['main']['App']['DoLogin'](arg1, arg2);
}

export function GetCustomerDetails(arg1) {
  return window['go']['main']['App']['GetCustomerDetails'](arg1);
}

export function GetCustomerForm(arg1) {
  return window['go']['main']['App']['GetCustomerForm'](arg1);
}

export function GetCustomerList() {
  return window['go']['main']['App']['GetCustomerList']();
}

export function GetDashboard() {
  return window['go']['main']['App']['GetDashboard']();
}

export function GetLoginPageHTML(arg1) {
  return window['go']['main']['App']['GetLoginPageHTML'](arg1);
}

export function GetProductListHTML() {
  return window['go']['main']['App']['GetProductListHTML']();
}

export function GetPurchaseForm(arg1) {
  return window['go']['main']['App']['GetPurchaseForm'](arg1);
}

export function GetPurchaseList() {
  return window['go']['main']['App']['GetPurchaseList']();
}

export function GetSaleForm(arg1) {
  return window['go']['main']['App']['GetSaleForm'](arg1);
}

export function GetSaleList() {
  return window['go']['main']['App']['GetSaleList']();
}

export function ProductForm(arg1) {
  return window['go']['main']['App']['ProductForm'](arg1);
}

export function SetToken(arg1) {
  return window['go']['main']['App']['SetToken'](arg1);
}
