// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {viewModels} from '../models';

export function DoLogin(arg1:string,arg2:string):Promise<viewModels.LoginResult>;

export function GetLoginPageHTML(arg1:string):Promise<string>;

export function SetToken(arg1:string):Promise<void>;
