// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {viewModels} from '../models';

export function DoLogin(arg1:string,arg2:string):Promise<viewModels.LoginResult>;

export function GetCustomerDetails(arg1:number):Promise<string>;

export function GetCustomerForm(arg1:number):Promise<string>;

export function GetCustomerList():Promise<string>;

export function GetDashboard():Promise<string>;

export function GetLoginPageHTML(arg1:string):Promise<string>;

export function GetProductListHTML():Promise<string>;

export function GetPurchaseForm(arg1:number):Promise<string>;

export function GetPurchaseList():Promise<string>;

export function GetSaleForm(arg1:number):Promise<string>;

export function GetSaleList():Promise<string>;

export function ProductForm(arg1:number):Promise<string>;

export function SetToken(arg1:string):Promise<void>;
