// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DoLogin(arg1, arg2) {
  return window['go']['main']['App']['DoLogin'](arg1, arg2);
}

export function GetLoginPageHTML(arg1) {
  return window['go']['main']['App']['GetLoginPageHTML'](arg1);
}

export function SetToken(arg1) {
  return window['go']['main']['App']['SetToken'](arg1);
}
